"""Auto-DJ — learns music taste over time and auto-queues songs Deagz will like."""

import json
import datetime
import threading
from pathlib import Path

from jarvis.tools.base import Tool, registry

MUSIC_LOG = Path(__file__).parent.parent.parent / "data" / "memory" / "music_taste.json"

_dj_running = False
_dj_thread = None


def _load_taste() -> dict:
    if MUSIC_LOG.exists():
        return json.loads(MUSIC_LOG.read_text(encoding="utf-8"))
    return {"artists": {}, "genres": {}, "recent_tracks": [], "liked": [], "disliked": []}


def _save_taste(data: dict):
    MUSIC_LOG.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def _track_listen(artist: str, track: str, genre: str = ""):
    """Record what the user listened to."""
    taste = _load_taste()

    # Count artist plays
    taste["artists"][artist] = taste["artists"].get(artist, 0) + 1

    # Count genre plays
    if genre:
        taste["genres"][genre] = taste["genres"].get(genre, 0) + 1

    # Recent tracks (last 100)
    taste["recent_tracks"].append({
        "artist": artist, "track": track, "genre": genre,
        "ts": datetime.datetime.now().isoformat()
    })
    if len(taste["recent_tracks"]) > 100:
        taste["recent_tracks"] = taste["recent_tracks"][-100:]

    _save_taste(taste)


def auto_dj(mood: str = "", duration: int = 30, **kwargs) -> str:
    """Start Auto-DJ mode — queues songs based on learned taste + optional mood."""
    try:
        from jarvis.tools.spotify import _get_spotify
        sp = _get_spotify()
        if not sp:
            return "Spotify not configured."

        taste = _load_taste()

        # Get top artists from listening history
        top_artists = sorted(taste.get("artists", {}).items(), key=lambda x: x[1], reverse=True)[:5]

        # Get recently played from Spotify for more context
        try:
            recent = sp.current_user_recently_played(limit=20)
            for item in recent.get("items", []):
                track = item.get("track", {})
                artist = track.get("artists", [{}])[0].get("name", "")
                if artist:
                    _track_listen(artist, track.get("name", ""), "")
        except Exception:
            pass

        # Build seed tracks from top artists + mood
        seed_artists = []
        seed_tracks = []

        # Get artist IDs for top listened artists
        for artist_name, count in top_artists[:3]:
            try:
                results = sp.search(q=artist_name, type="artist", limit=1)
                items = results.get("artists", {}).get("items", [])
                if items:
                    seed_artists.append(items[0]["id"])
            except Exception:
                pass

        # If mood specified, find a seed track for it
        if mood:
            try:
                results = sp.search(q=mood, type="track", limit=3)
                for t in results.get("tracks", {}).get("items", [])[:2]:
                    seed_tracks.append(t["id"])
            except Exception:
                pass

        # If no seeds, use recent tracks
        if not seed_artists and not seed_tracks:
            try:
                recent = sp.current_user_recently_played(limit=5)
                for item in recent.get("items", [])[:5]:
                    seed_tracks.append(item["track"]["id"])
            except Exception:
                pass

        if not seed_artists and not seed_tracks:
            return "Not enough listening history yet. Play some music first and I'll learn your taste."

        # Get recommendations
        rec_params = {"limit": min(duration, 50)}
        if seed_artists:
            rec_params["seed_artists"] = seed_artists[:5]
        if seed_tracks:
            rec_params["seed_tracks"] = seed_tracks[:max(0, 5 - len(seed_artists))]

        recs = sp.recommendations(**rec_params)
        track_uris = [t["uri"] for t in recs.get("tracks", [])]

        if not track_uris:
            return "Couldn't generate recommendations. Try playing more music first."

        # Create a queue or start playback
        devices = sp.devices()
        active = None
        for d in devices.get("devices", []):
            if d.get("is_active"):
                active = d["id"]
                break
        if not active and devices.get("devices"):
            active = devices["devices"][0]["id"]

        if not active:
            return "No Spotify device found. Open Spotify first."

        # Create a temporary playlist
        user = sp.current_user()
        timestamp = datetime.datetime.now().strftime("%I:%M %p")
        playlist_name = f"JARVIS DJ — {mood or 'Your Vibe'} ({timestamp})"
        playlist = sp.user_playlist_create(user["id"], playlist_name, public=False,
            description=f"Auto-generated by JARVIS based on your listening history")
        sp.playlist_add_items(playlist["id"], track_uris)
        sp.shuffle(True, device_id=active)
        sp.start_playback(device_id=active, context_uri=playlist["uri"])

        # Get first few artist names for the response
        artists = set()
        for t in recs.get("tracks", [])[:5]:
            artists.add(t.get("artists", [{}])[0].get("name", ""))
        artist_list = ", ".join(list(artists)[:4])

        top_listened = ", ".join([a[0] for a in top_artists[:3]]) if top_artists else "your recent plays"

        return f"Auto-DJ started with {len(track_uris)} tracks. Based on your taste ({top_listened}), mixing in {artist_list} and more. {mood + ' vibes.' if mood else ''}"

    except Exception as e:
        return f"Auto-DJ failed: {e}"


def rate_song(rating: str = "like", **kwargs) -> str:
    """Rate the current song as liked or disliked to improve recommendations."""
    try:
        from jarvis.tools.spotify import _get_spotify
        sp = _get_spotify()
        if not sp:
            return "Spotify not configured."

        current = sp.current_playback()
        if not current or not current.get("item"):
            return "Nothing is playing."

        track = current["item"]
        name = track.get("name", "Unknown")
        artist = track.get("artists", [{}])[0].get("name", "Unknown")

        taste = _load_taste()
        entry = {"track": name, "artist": artist, "ts": datetime.datetime.now().isoformat()}

        if rating.lower() in ("like", "love", "yes", "good", "fire"):
            taste.setdefault("liked", []).append(entry)
            # Boost artist weight
            taste["artists"][artist] = taste["artists"].get(artist, 0) + 3
            _save_taste(taste)

            # Also save to Spotify liked songs
            try:
                sp.current_user_saved_tracks_add([track["id"]])
            except Exception:
                pass

            return f"Noted — you like '{name}' by {artist}. I'll queue more like this."
        else:
            taste.setdefault("disliked", []).append(entry)
            # Reduce artist weight
            taste["artists"][artist] = max(0, taste["artists"].get(artist, 0) - 2)
            _save_taste(taste)

            # Skip the song
            try:
                sp.next_track()
            except Exception:
                pass

            return f"Skipping '{name}' — I'll avoid similar tracks."

    except Exception as e:
        return f"Rating failed: {e}"


def get_music_taste(**kwargs) -> str:
    """Show what Jarvis has learned about the user's music taste."""
    taste = _load_taste()
    if not taste.get("artists"):
        return "Haven't learned your taste yet. Play some music and I'll start tracking."

    top = sorted(taste["artists"].items(), key=lambda x: x[1], reverse=True)[:10]
    lines = ["Your top artists (by play count):"]
    for artist, count in top:
        lines.append(f"  {artist}: {count} plays")

    liked = taste.get("liked", [])
    if liked:
        lines.append(f"\nLiked songs: {len(liked)}")
        for s in liked[-5:]:
            lines.append(f"  ♥ {s['track']} — {s['artist']}")

    return "\n".join(lines)


# ─── Register ───

registry.register(Tool(
    name="auto_dj",
    description="Start Auto-DJ mode — plays music based on learned taste and optional mood. Use for 'be my DJ', 'play something I'd like', 'DJ mode', 'play music based on my taste'. Mood examples: 'chill', 'hype', 'sad', 'study', 'workout'.",
    parameters={
        "type": "object",
        "properties": {
            "mood": {"type": "string", "description": "Optional mood/vibe (chill, hype, study, workout, sad, late night)"},
            "duration": {"type": "integer", "description": "Number of songs to queue (default 30)"},
        },
    },
    handler=auto_dj,
))

registry.register(Tool(
    name="rate_song",
    description="Rate the current song to improve Auto-DJ. Use for 'I like this song', 'skip this is bad', 'this is fire', 'not feeling this one'.",
    parameters={
        "type": "object",
        "properties": {
            "rating": {"type": "string", "description": "'like' or 'dislike'"},
        },
        "required": ["rating"],
    },
    handler=rate_song,
))

registry.register(Tool(
    name="get_music_taste",
    description="Show what Jarvis has learned about the user's music taste. Use for 'what music do I like', 'what's my taste', 'show my top artists'.",
    parameters={"type": "object", "properties": {}},
    handler=get_music_taste,
))
